[workspace]
authors = ["Johannes Röttenbacher <jr-alias@posteo.de>"]
channels = ["conda-forge"]
name = "ftp_sync"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
tqdm = ">=4.67.1,<5"

[pypi-dependencies]
dotenv = ">=0.9.9, <0.10"
